In [4]:
import os 
import pandas as pd
import numpy as np
from tqdm import tqdm

# Reuters21578

In [ ]:
label_path = r'C:\Users\IsmailKaraman\workspace\GitHub\thesis\data\Reuters21578\cats.txt'
test_path = r'C:\Users\IsmailKaraman\workspace\GitHub\thesis\data\Reuters21578\test'
train_path = r'C:\Users\IsmailKaraman\workspace\GitHub\thesis\data\Reuters21578\training'

In [3]:
data = {}
for path in [test_path, train_path]:
    for i in os.listdir(path):
        with open(path + '\\' + i) as f:
            data[i] = f.read()

In [4]:
with open(label_path) as f:
    labels_raw = f.readlines()

In [5]:
labels = {}
for line in labels_raw:
    splitted_line = line.replace('\n','').split(' ')
    idx = splitted_line[0].split('/')[1]
    label = ' '.join(splitted_line[1:])
    labels[idx] = label

In [6]:
data_df = pd.DataFrame.from_dict(data, orient='index', columns=['text'])
label_df = pd.DataFrame.from_dict(labels, orient='index', columns=['label'])
df_raw = pd.concat([data_df, label_df], axis=1).reset_index()

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
df = pd.DataFrame(vectorizer.fit_transform(df_raw['label']).toarray(), columns=vectorizer.get_feature_names())
df['text'] = df_raw['text']

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [8]:
df.head(3)

,acq,alum,barley,bop,cake,carcass,castor,cattle,chem,cocoa,...,supply,tea,tin,trade,veg,wheat,wpi,yen,zinc,text
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,ASIAN EXPORTERS FEAR DAMAGE FROM U.S.-JAPAN RI...
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,CHINA DAILY SAYS VERMIN EAT 7-12 PCT GRAIN STO...
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,JAPAN TO REVISE LONG-TERM ENERGY DEMAND DOWNWA...
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,THAI TRADE DEFICIT WIDENS IN FIRST QUARTER\n ...
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,INDONESIA SEES CPO PRICE RISING SHARPLY\n Ind...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10783,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,U.K. MONEY MARKET SHORTAGE FORECAST REVISED DO...
10784,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,KNIGHT-RIDDER INC &lt;KRN> SETS QUARTERLY\n Q...
10785,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,TECHNITROL INC &lt;TNL> SETS QUARTERLY\n Qtly...
10786,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NATIONWIDE CELLULAR SERVICE INC &lt;NCEL> 4TH ...
10787,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,&lt;A.H.A. AUTOMOTIVE TECHNOLOGIES CORP> YEAR ...

In [9]:
df.to_csv('Reuters21578.csv', index=False)

# ohsumed
https://paperswithcode.com/dataset/ohsumed

In [2]:
path = r'C:\Users\IsmailKaraman\workspace\GitHub\thesis\data\ohsumed\ohsumedDataset'

In [19]:
data = {}
labels = {}
for folder in tqdm(os.listdir(path)[:-1]):
    for file in os.listdir(path+'\\'+folder):
        with open(path+'\\'+folder+'\\'+file) as f:
            data[file] = f.read()
            if file in labels:
                labels[file].append(folder)
            else:
                labels[file] = [folder]

100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [07:38<00:00, 30.54s/it]

In [27]:
labels = {k:' '.join(v) for k,v in labels.items()}

In [36]:
label_df = pd.DataFrame.from_dict(labels, orient='index', columns=['label'])
data_df = pd.DataFrame.from_dict(data, orient='index', columns=['text'])
df_raw = pd.concat([data_df, label_df], axis=1).reset_index()

In [38]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
df = pd.DataFrame(vectorizer.fit_transform(df_raw['label']).toarray(), columns=vectorizer.get_feature_names())
df['text'] = df_raw['text']

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [40]:
df.to_csv('ohsumed.csv', index=False)